import pandas as pd


def build_prophet_model():
    from pathlib import Path

    import prophet
    from prophet import Prophet

    if prophet.__file__ is None:
        raise RuntimeError("Prophet 安装路径不可用")
    prophet_pkg_dir = Path(prophet.__file__).resolve().parent
    makefile = prophet_pkg_dir / "stan_model" / "cmdstan-2.33.1" / "makefile"
    if not makefile.exists():
        makefile.write_text("# generated by TrendForecasting\n", encoding="utf-8")

    return Prophet(
        seasonality_mode="additive",
        interval_width=0.8,
    )


def run_forecast(rows: list[dict], periods: int) -> dict:
    if len(rows) < 3:
        raise ValueError("rows 至少 3 条")

    frame = pd.DataFrame(rows)
    if "date" not in frame.columns or "value" not in frame.columns:
        raise ValueError("数据列必须包含 date/value")

    frame = frame.rename(columns={"date": "ds", "value": "y"})
    frame["ds"] = pd.to_datetime(frame["ds"], format="%Y-%m-%d", errors="coerce")
    frame["y"] = pd.to_numeric(frame["y"], errors="coerce")
    frame = frame.dropna(subset=["ds", "y"]).sort_values("ds")

    if frame.shape[0] < 3:
        raise ValueError("有效数据不足，至少需要 3 条")

    model = build_prophet_model()
    model.fit(frame)

    future = model.make_future_dataframe(periods=periods, freq="D", include_history=True)
    forecast = model.predict(future)

    forecast_output = (
        forecast[["ds", "yhat", "yhat_lower", "yhat_upper"]]
        .copy()
        .assign(ds=lambda d: d["ds"].dt.strftime("%Y-%m-%d"))
    )

    history_output = (
        frame[["ds", "y"]]
        .copy()
        .assign(ds=lambda d: d["ds"].dt.strftime("%Y-%m-%d"))
    )

    history = [
        {"date": row["ds"], "value": float(row["y"])}
        for row in history_output.to_dict(orient="records")
    ]
    pred = [
        {
            "date": row["ds"],
            "yhat": float(row["yhat"]),
            "yhat_lower": float(row["yhat_lower"]),
            "yhat_upper": float(row["yhat_upper"]),
        }
        for row in forecast_output.to_dict(orient="records")
    ]

    return {
        "history": history,
        "forecast": pred,
    }
